name: ${project.name}
main: fr.pmk.lucksecure.bukkit.BukkitLuckSecure
version: ${project.version}
authors: [ Clem_Fern ]
depend: [ LuckPerms ]
commands:
  lsauth:
    description: LuckSecure Authentication Command
  lsauth-reset:
    description: LuckSecure Reset Player TOTP Secret Command
  lsauth-status:
    description: LuckSecure Display Player TOTP Status Command