name: ${project.parent.name}
version: ${project.parent.version}
main: fr.pmk.lucksecure.paper.Main
authors: [ PumpMyKins , Clem_Fern ]
depend: [ LuckPerms ]
api-version: '1.21.1'
libraries:
  - org.apache.commons:commons-configuration2:2.11.0
  - com.amdelamar:jotp:1.3.0
  - com.j256.ormlite:ormlite-jdbc:6.1
  - com.h2database:h2:2.3.232
  - redis.clients:jedis:5.2.0
commands:
  lsauth:
    description: LuckSecure Authentication Command
  lsauth-reset:
    description: LuckSecure Reset Player TOTP Secret Command
  lsauth-status:
    description: LuckSecure Display Player TOTP Status Command